# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    
    docker:
      - image: circleci/android:api-26-alpha
        environment:
        - JVM_OPTS: -Xmx3200m
        - TERM: dumb
        
      - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_USER: postgres
      
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: sudo apt-get install postgresql-client
      
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1
          
      - run:
          name: Running Test
          command: |
            psql -c "create database Users" -U postgres -h localhost -p 5432
            psql -c "create table Users(ID INT PRIMARY KEY NOT NULL, NAME TEXT NOT NULL)" -U postgres -h localhost -p 5432
            psql -c "create user $DB_USERNAME with password '$DB_PASSWORD'" -U postgres -h localhost -p 5432     
            psql -c "alter user $DB_USERNAME with superuser" -U postgres -h localhost -p 5432      
      
      
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
         command: sudo chmod +x ./gradlew
      
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      
      - run:
          name: Run Tests
          command: ./gradlew lint test
      
      - store_artifacts:
          path: app/build/reports
          destination: reports
      
      - store_test_results:
          path: app/build/test-results
          
      - run:
          name: Build APK
          command: ./gradlew assembleRelease

      - store_artifacts:
            path: app/build/outputs/apk/
            destination: apks/

      - save_cache:
                key: anysoftkeyboard-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                paths:
                  - "~/.gradle/3.4.1"
                  - "~/.gradle/wrapper/dists/gradle-3.4.1-bin"
                  - "~/.gradle/caches/modules-2"
                  - "~/.gradle/buildOutputCleanup"
                  - "~/.m2"
                  
      - run:
          name: JFrog
          command: (cp app/build/outputs/apk/release/app-release-unsigned.apk "app/build/outputs/apk/release/app-release-v$CIRCLE_BUILD_NUM.apk" || echo "Erreur de copie") && curl -T "app/build/outputs/apk/release/app-release-v$CIRCLE_BUILD_NUM.apk" "$ARTIFACTORY_URL"          
                  